### ISSUE TITLE
The outputs of NRN

### ISSUE THREAD

**Issue by asdjia** [Ysz2022/NeRCo#11]
Thank you for your outstanding work.

While attempting to obtain outputs using NRN exclusively, I observed the presence of abnormal pixels in almost every resulting image (please refer to the attached images). Could you kindly provide an explanation for their occurrence and clarify the reason behind this phenomenon? Thank you!
![Parking_pre_A](https://github.com/Ysz2022/NeRCo/assets/44183247/2af541a1-9ce7-441b-98db-4d76884f7d61)
![night (29)_pre_A](https://github.com/Ysz2022/NeRCo/assets/44183247/94d26c98-49ac-4c40-958b-2ccad6bb0942)
![night (24)_pre_A](https://github.com/Ysz2022/NeRCo/assets/44183247/339ef824-b422-4820-980c-f0fc4aac15b1)

**Comment by Ysz2022** [comment]
Thanks for your interest in our work! :)

Indeed, sometimes noise may appear in the output of NRN, this is because NRN cannot totally fit to its input image (and that is also the reason why it can normalize lightness), which leads to noise. Note that not only our method, other approaches which aims to normalization also exhibit inevitable information loss. We believe that the reason why the output of NRN contains noise is due to the inevitable information loss during normalization, and that is why we concat the original input to the reproduced image at the end of NRN, which aims to fuse features to complete missing information.

If you have further questions, please tell me and I will try my best to answer them :)
